codecov:
  require_ci_to_pass: yes
  token: 48801ecb-9e80-4b65-9b3c-53ad8d08c814

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: 'condensed_header, condensed_files, condensed_footer'
  behavior: new
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
