name: pnpm 성능 테스트

on:
  push:
    branches:
      - main

jobs:
  pnpm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: pnpm 설치
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: pnpm 캐시 설정
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/pnpm/store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
            ${{ runner.os }}-

      - name: 캐시 상태 출력
        run: |
          if [[ "${{ steps.pnpm-cache.outputs.cache-hit }}" == 'true' ]]; then
            echo "캐시 히트: true"
          else
            echo "캐시 히트: false"
          fi

      - name: 캐시 디버깅
        run: |
          echo "현재 디렉토리: $(pwd)"
          echo "pnpm-lock.yaml 해시: ${{ hashFiles('**/pnpm-lock.yaml') }}"
          echo "캐시 키: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}"
          echo "캐시 상태: ${{ steps.pnpm-cache.outputs.cache-hit }}"
          echo "=== pnpm store path ==="
          pnpm store path
          echo "=== 디렉토리 구조 ==="
          ls -la
          echo "=== pnpm store 확인 ==="
          ls -la ~/.local/share/pnpm/store || echo "pnpm store 없음"
          echo "=== node_modules 확인 ==="
          ls -la node_modules || echo "node_modules 없음"

      - name: pnpm 캐시 위치 확인
        run: |
          pnpm store path

      - name: pnpm 설치 및 빌드 시간 측정
        run: |
          echo "=== pnpm 테스트 시작 ==="
          echo "캐시 상태: ${{ steps.pnpm-cache.outputs.cache-hit }}"
          echo "pnpm install 시작"
          time pnpm install
          echo "pnpm run build 시작"
          time pnpm run build
          echo "=== pnpm 테스트 종료 ==="

      - name: pnpm 설치 및 캐시 확인
        run: |
          pnpm install
          echo "=== 설치 후 캐시 상태 ==="
          ls -la ~/.pnpm-store
          du -sh ~/.pnpm-store
